### ISSUE TITLE
Grammar & Markup Issues

### ISSUE THREAD

**Issue by pjhampton** [barrel-db/barrel-www#2]
@benoitc there are a couple of issues with the current spelling and grammar on the website. For example 

> your data are safe

should be,

> your data is safe

I can clean these up pretty quickly. There a couple of minor issues with the HTML markup and CSS, do you want me to clean this up too or would you rather me hold off? I'm not sure what the plans are for the website.

**Comment by benoitc** [comment]
@pjhampton i update it with some content from https://speakerdeck.com/benoitc/barrel-using-erlang-to-build-a-database . should be done tonight. Any help on the wording and other typos is much appreciated :) Thanks!

**Comment by pjhampton** [comment]
On it @benoitc ! I will wait for your updates just incase the links need updated to docs etc.
